# example profiles.yml file
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      user: postgres
      password: 7ujm8ik,
      port: 5432
      dbname: jaffle_shop
      schema: dbt_alice
      threads: 4